/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/3/landlord-30101.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/3/landlord-30102.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/3/landlord-30103.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/3/landlord-30104.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/3/landlord-30105.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/3/landlord-30106.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/3/landlord-30107.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/3/landlord-30108.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/3/landlord-30109.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/3/landlord-30110.conf -D
