/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/6/landlord-30251.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/6/landlord-30252.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/6/landlord-30253.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/6/landlord-30254.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/6/landlord-30255.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/6/landlord-30256.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/6/landlord-30257.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/6/landlord-30258.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/6/landlord-30259.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/6/landlord-30260.conf -D
