/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/4/landlord-30151.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/4/landlord-30152.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/4/landlord-30153.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/4/landlord-30154.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/4/landlord-30155.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/4/landlord-30156.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/4/landlord-30157.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/4/landlord-30158.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/4/landlord-30159.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/4/landlord-30160.conf -D
