#ifndef __TASKS_TYPE_H__
#define __TASKS_TYPE_H__

enum task_type_code
{
	TT_PLAY_TIME = 101,
	TT_WIN_TIME,
	TT_LAND_SPRING,
	TT_FARMER_SPRING,
	TT_WIN_MULT,
	TT_WIN_CONT_TIME,
	TT_LAND_WIN_TIME,
	TT_FARMER_WIN_TIME,
	TT_WIN_MONEY,
	TT_HOLE_NO_7,
	TT_HOLE_LESS_K,
	TT_HOLE_ROCKET_BOMB_2,

	TT_BCARDS_DOUB = 201,
	TT_BCARDS_THREE,
	TT_BCARDS_FLOWER,
	TT_BCARDS_JUNKO,
	TT_BCARDS_FLOWER_JUNKO,
	TT_BCARDS_KING,
	TT_BCARDS_ROCKET,

	TT_PLAY_PLANE = 301,
	TT_PLAY_BOMB_GREAT,
	TT_PLAY_BOMB,
	TT_PLAY_ROCKET,
	TT_PLAY_FOURBY_TWO,
	TT_PLAY_CONT_DOUB,
	TT_PLAY_JUNKO_BY,
	TT_PLAY_JUNKO_NUM,
	TT_PLAY_JUNKO_NUM_G,
	TT_PLAY_KING,
	TT_PLAY_DOUB,
	TT_PLAY_ONCE,

	TT_END_DOUB = 401,
	TT_END_THREEBY_TWO,
	TT_END_THREEBY_ONE,
	TT_END_JUNKO
};

#endif
