/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/5/landlord-30201.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/5/landlord-30202.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/5/landlord-30203.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/5/landlord-30204.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/5/landlord-30205.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/5/landlord-30206.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/5/landlord-30207.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/5/landlord-30208.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/5/landlord-30209.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/5/landlord-30210.conf -D
