/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/2/landlord-30051.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/2/landlord-30052.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/2/landlord-30053.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/2/landlord-30054.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/2/landlord-30055.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/2/landlord-30056.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/2/landlord-30057.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/2/landlord-30058.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/2/landlord-30059.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/2/landlord-30060.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/2/landlord-30061.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/2/landlord-30062.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/2/landlord-30063.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/2/landlord-30064.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/2/landlord-30065.conf -D
