/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/1/landlord-30001.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/1/landlord-30002.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/1/landlord-30003.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/1/landlord-30004.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/1/landlord-30005.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/1/landlord-30006.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/1/landlord-30007.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/1/landlord-30008.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/1/landlord-30009.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/1/landlord-30010.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/1/landlord-30011.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/1/landlord-30012.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/1/landlord-30013.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/1/landlord-30014.conf -D
/usr/local/nddz/landlord/landlord -f /usr/local/nddz/landlord/conf/1/landlord-30015.conf -D
